### ISSUE TITLE
Xcode 14 beta 1: issues with Regex and Xcode previews

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-case-paths#81]
> **Note**: If you've encountered any of the issues mentioned below, please share the details on the Swift forums as outlined [here](https://forums.swift.org/t/se-0354-second-review-regex-literals/57367/112).

If you've tried to use Case Paths in the first Xcode 14 beta, you may have noticed a few issues around the Regex literals. Please note that these are not issues with Case Paths the library, and are instead more general bugs with Apple's software.

While Apple appears to be aware of these issues, feel free to [file feedback](https://feedback.apple.com) if any of them affect you, and we can hope for a speedy resolution in the next beta.

Issues (and some workarounds) are as follows:

  - Xcode previews in files that contain case paths will fail to run. This is a [known issue](https://forums.swift.org/t/se-0354-second-review-regex-literals/57367/100). A workaround involves introducing a trailing comment to any line that contains a case path:

    ```diff
    -.compactMap(/Result.success)
    +.compactMap(/Result.success)  // NB: comment works around Xcode 14b1 previews bug
    ```

  - Usage of case paths can break Xcode syntax highlighting and indentation. There's no known workaround at this time (outside of using Xcode 13, instead), but if you find one, please share in a comment!

  - Xcode projects may default to "bare" syntax, which can break usage of case paths, especially when multiple are used on the same line. To fix, explicitly wrap any additional case path that appears on a single line with parentheses:

    ```diff
    -.pullback(state: /AppState.login, action: /AppAction.login)
    +.pullback(state: /AppState.login, action: (/AppAction.login))
    ```

    Or rewrite the same expressions over multiple lines to avoid having more than one case path per line:

    ```diff
    -.pullback(state: /AppState.login, action: /AppAction.login)
    +.pullback(
    +  state: /AppState.login,
    +  action: /AppAction.login
    +)
    ```

Related discussions:

- #75 
- #77
- #80

**Comment by lukesutton** [comment]
And a work around appears just like that! You legend. Thank you.

**Comment by kaishin** [comment]
Did anyone come up with a minimal reproduction case I can attach when submitting feedback? I can get around making one myself but thought I'd check first.

**Comment by stephencelis** [comment]
We just released 0.9.0, which comes with an alternative interface for creating case paths:

```swift
/Enum.case

// vs.

CasePath(Enum.case)
```

We hope this will provide a temporary workaround for folks experiencing issues with Xcode 14!

**Comment by kaishin** [comment]
> We hope this will provide a temporary workaround for folks experiencing issues with Xcode 14!

A reasonable trade-off! Thank you for introducing this. 
This syntax might in fact grow on me as I usually prefer spelling things out.

**Comment by davdroman** [comment]
![Screen Shot 2022-06-22 at 19 40 24](https://user-images.githubusercontent.com/2538074/175112275-ba2dff7c-84fb-4132-87ec-3f76e42148fc.png)

Seems like this got fixed in Xcode 14 beta 2.

**Comment by stephencelis** [comment]
Going to close this out then! Still some syntax coloring issues but hopefully that will be fixed in the future too.

**Comment by tgrapperon** [comment]
@stephencelis In my experience, syntax highlighting and indentation are the only thing that effectively improved!
Both screenshots are from Xcode 14b2. With the trailing comment, we get Previews & highlighting. Without, we're in the same state as beta1. Am I alone in this case?
<img width="1182" alt="Xcode 14b2 issue" src="https://user-images.githubusercontent.com/35562418/175197816-845e0590-0d34-4ce7-aa42-dd158226cd98.png">
<img width="1182" alt="Xcode 14b2 workaround" src="https://user-images.githubusercontent.com/35562418/175197976-67d4304f-034a-47d3-8218-3595e9b2ad39.png">

**Comment by stephencelis** [comment]
@tgrapperon The highlighting is definitely still broken in your first image, and I've seen the same. I can corroborate issues with previews, which is unfortunate, and should definitely be reported. We can only hope for a more stable beta 3!

**Comment by tgrapperon** [comment]
@stephencelis Last year's Xcode beta cycle was way worse in terms of highlighting/completion.
But the real issue there is that SwiftUI Previews are still not fixed. They still fail to build with uncommented `CasePaths`. I'm also hopeful it will be solved as Previews catch up later in the cycle, but this issue is still present, with the same regex literal error message. From the comments above, I was under the impression they were fixed.

**Comment by stephencelis** [comment]
@tgrapperon We can definitely reopen and pin this issue given the problems, though it's out of our control 😞 We can at least re-encourage more feedback to Apple given the persisting problem.
